# Generated by Django 5.1.1 on 2024-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0002_alter_generatedvalue_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedvalue",
            name="value",
        ),
        migrations.AddField(
            model_name="generatedvalue",
            name="conan_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="generatedvalue",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedvalue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="generatedvalue",
            name="some_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
