# Generated by Django 5.1.1 on 2024-10-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0004_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrderServingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("date", models.DateField(auto_now_add=True)),
                ("looks_of_food", models.TextField()),
                (
                    "visual_representation",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/serving_time/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerOrderWaitingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "visual_representation",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/waiting_time/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="categories",
            name="URL",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
