# Generated by Django 5.1.1 on 2024-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_Server",
            "0005_customerorderservingtime_customerorderwaitingtime_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorderservingtime",
            name="table_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerorderwaitingtime",
            name="table_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
