# Generated by Django 5.1.2 on 2025-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_Server", "0006_customerorderservingtime_table_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
